name: todo_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  wolt_modal_sheet: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bootstrap_icons: ^1.11.1
  logger: ^2.0.2+1
  flutter_dotenv: ^5.0.2
  http: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
        - asset: assets/font/Poppins/Poppins-Medium.ttf
        - asset: assets/font/Poppins/Poppins-Italic.ttf
  assets:
    - assets/
    - .env