version: '3.8'
services:
  nest-api:
    build:
      dockerfile: Dockerfile
      context: ./nest-api
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: ${POSTGRES_URL}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - ${NEST_API_PORT}:8080
    depends_on:
      - psql-database

  java-api:
    build:
      dockerfile: Dockerfile
      context: ./java-api
    ports:
      - ${JAVA_API_PORT}:8080
    depends_on:
      - psql-database

  psql-database:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - todos:/var/lib/postgresql/data

volumes:
  todos:


